In [1]:
import pandas as pd

In [17]:
fortune = pd.read_csv("fortune1000.csv", index_col = "Rank")
sectors = fortune.groupby("Sector")
fortune.head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000

In [18]:
type(fortune)

pandas.core.frame.DataFrame

In [19]:
type(sectors)

pandas.core.groupby.generic.DataFrameGroupBy

In [20]:
# There are 21 unique groupings
len(sectors)

21

In [22]:
# This can be proven by using .nunique()
fortune["Sector"].nunique()

21

In [24]:
# Similar to value_counts of unique items in the sector
sectors.size()

Sector
Aerospace & Defense              20
Apparel                          15
Business Services                51
Chemicals                        30
Energy                          122
Engineering & Construction       26
Financials                      139
Food and Drug Stores             15
Food, Beverages & Tobacco        43
Health Care                      75
Hotels, Resturants & Leisure     25
Household Products               28
Industrials                      46
Materials                        43
Media                            25
Motor Vehicles & Parts           24
Retailing                        80
Technology                      102
Telecommunications               15
Transportation                   36
Wholesalers                      40
dtype: int64

In [26]:
# .first() will pull first row of each grouping
# .last() will provide the last row of each grouping
sectors.first()

,Company,Industry,Location,Revenue,Profits,Employees
Sector,,,,,,
Aerospace & Defense,Boeing,Aerospace and Defense,"Chicago, IL",96114,5176,161400
Apparel,Nike,Apparel,"Beaverton, OR",30601,3273,62600
Business Services,ManpowerGroup,Temporary Help,"Milwaukee, WI",19330,419,27000
Chemicals,Dow Chemical,Chemicals,"Midland, MI",48778,7685,49495
Energy,Exxon Mobil,Petroleum Refining,"Irving, TX",246204,16150,75600
Engineering & Construction,Fluor,"Engineering, Construction","Irving, TX",18114,413,38758
Financials,Berkshire Hathaway,Insurance: Property and Casualty (Stock),"Omaha, NE",210821,24083,331000
Food and Drug Stores,CVS Health,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
"Food, Beverages & Tobacco",Archer Daniels Midland,Food Production,"Chicago, IL",67702,1849,32300
Health Care,McKesson,Wholesalers: Health Care,"San Francisco, CA",181241,1476,70400
"Hotels, Resturants & Leisure",McDonald’s,Food Services,"Oak Brook, IL",25413,4529,420000
Household Products,Procter & Gamble,Household and Personal Products,"Cincinnati, OH",78756,7036,110000
Industrials,General Electric,Industrial Machinery,"Fairfield, CT",140389,-6126,333000
Materials,Alcoa,Metals,"New York, NY",22534,-322,60000
Media,Disney,Entertainment,"Burbank, CA",52465,8382,185000
Motor Vehicles & Parts,General Motors,Motor Vehicles and Parts,"Detroit, MI",152356,9687,215000
Retailing,Walmart,General Merchandisers,"Bentonville, AR",482130,14694,2300000
Technology,Apple,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000
Telecommunications,AT&T,Telecommunications,"Dallas, TX",146801,13345,281450
Transportation,UPS,"Mail, Package, and Freight Delivery","Atlanta, GA",58363,4844,341240
Wholesalers,Sysco,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [27]:
# .groups() provides a dictionary. keys is the group, values is a list of index labels
sectors.groups

{'Aerospace & Defense': [24, 45, 60, 88, 118, 120, 209, 245, 282, 378, 389, 490, 560, 605, 785, 788, 836, 903, 958, 987], 'Apparel': [91, 231, 340, 354, 448, 547, 575, 597, 683, 695, 726, 794, 877, 882, 917], 'Business Services': [144, 186, 199, 204, 221, 248, 249, 294, 307, 312, 355, 392, 404, 440, 467, 468, 481, 485, 492, 503, 545, 626, 635, 652, 677, 694, 714, 729, 734, 735, 737, 744, 767, 776, 777, 783, 791, 792, 796, 801, 803, 816, 819, 820, 869, 870, 886, 939, 951, 952, 993], 'Chemicals': [56, 101, 182, 189, 206, 253, 262, 277, 288, 296, 316, 538, 549, 555, 566, 580, 613, 624, 654, 668, 717, 720, 724, 758, 761, 829, 865, 898, 934, 949], 'Energy': [2, 14, 30, 32, 42, 65, 90, 95, 98, 104, 115, 117, 121, 162, 163, 165, 166, 175, 178, 188, 190, 192, 193, 198, 214, 216, 217, 223, 225, 229, 243, 246, 247, 257, 272, 274, 279, 289, 319, 322, 324, 343, 348, 349, 350, 363, 364, 384, 387, 388, 394, 402, 403, 410, 425, 437, 438, 445, 458, 475, 483, 493, 507, 522, 541, 548, 556, 558, 569, 571, 579, 598, 600, 606, 633, 650, 656, 662, 679, 692, 696, 703, 703, 706, 711, 715, 732, 742, 743, 745, 754, 772, 784, 798, 802, 810, 817, 826, 843, 850, ...], 'Engineering & Construction': [155, 156, 235, 260, 301, 314, 352, 381, 433, 478, 498, 501, 516, 572, 576, 640, 719, 738, 822, 863, 874, 892, 929, 963, 985, 994], 'Financials': [4, 16, 23, 26, 27, 29, 35, 40, 43, 49, 50, 61, 69, 73, 74, 76, 78, 81, 82, 83, 85, 100, 105, 112, 114, 131, 135, 137, 152, 171, 179, 184, 205, 210, 222, 226, 227, 232, 236, 250, 252, 259, 264, 265, 271, 273, 275, 283, 298, 306, 311, 318, 326, 329, 332, 344, 347, 367, 368, 376, 382, 398, 401, 411, 421, 436, 442, 449, 453, 453, 471, 472, 472, 476, 479, 482, 486, 488, 494, 497, 499, 506, 509, 510, 520, 529, 531, 536, 540, 551, 561, 568, 573, 590, 603, 609, 611, 646, 651, 663, ...], 'Food and Drug Stores': [7, 17, 19, 87, 107, 160, 181, 595, 614, 631, 669, 756, 809, 849, 928], 'Food, Beverages & Tobacco': [41, 44, 62, 66, 84, 94, 106, 149, 153, 161, 176, 207, 215, 242, 266, 304, 336, 337, 362, 397, 413, 429, 452, 456, 460, 535, 542, 567, 574, 587, 608, 615, 636, 664, 686, 702, 770, 787, 795, 804, 889, 902, 954], 'Health Care': [5, 6, 12, 21, 22, 33, 39, 46, 52, 55, 63, 72, 79, 86, 123, 124, 125, 130, 138, 140, 141, 168, 172, 200, 201, 202, 263, 268, 278, 286, 287, 290, 291, 305, 325, 358, 359, 372, 420, 430, 431, 447, 457, 465, 469, 515, 527, 537, 553, 559, 583, 618, 629, 661, 684, 693, 697, 708, 746, 749, 766, 775, 790, 799, 815, 818, 845, 868, 881, 883, 935, 960, 965, 977, 978], 'Hotels, Resturants & Leisure': [109, 146, 195, 218, 241, 254, 309, 371, 444, 466, 534, 546, 557, 562, 585, 731, 763, 764, 779, 797, 895, 915, 918, 941, 999], 'Household Products': [34, 151, 174, 256, 261, 328, 338, 345, 370, 434, 441, 450, 455, 533, 550, 554, 601, 665, 699, 716, 856, 890, 900, 907, 932, 950, 967, 992], 'Industrials': [11, 59, 75, 93, 97, 128, 134, 148, 211, 224, 360, 377, 396, 412, 419, 539, 544, 596, 622, 623, 630, 645, 655, 658, 666, 674, 690, 757, 782, 789, 806, 813, 823, 831, 832, 835, 841, 847, 866, 867, 873, 887, 942, 947, 964, 1000], 'Materials': [126, 127, 170, 244, 251, 303, 321, 341, 356, 373, 375, 383, 417, 418, 426, 435, 446, 480, 489, 514, 518, 577, 586, 616, 617, 620, 625, 628, 637, 639, 641, 660, 667, 687, 691, 751, 774, 793, 857, 885, 911, 982, 986], 'Media': [53, 96, 99, 203, 213, 255, 327, 366, 406, 414, 525, 530, 681, 705, 707, 722, 741, 752, 759, 762, 821, 913, 968, 969, 989], 'Motor Vehicles & Parts': [8, 9, 70, 147, 154, 169, 281, 310, 334, 339, 424, 428, 470, 588, 591, 604, 647, 670, 718, 739, 811, 957, 961, 979], 'Retailing': [1, 15, 28, 38, 47, 71, 89, 103, 111, 132, 136, 139, 143, 145, 177, 180, 191, 196, 197, 228, 234, 237, 238, 240, 258, 267, 269, 280, 293, 297, 299, 302, 330, 342, 346, 361, 365, 374, 379, 380, 393, 415, 427, 439, 495, 500, 502, 511, 512, 517, 523, 582, 592, 602, 607, 610, 621, 643, 644, 648, 657, 675, 689, 721, 748, 771, 773, 807, 812, 824, 825, 827, 840, 876, 894, 899, 922, 937, 940, 973], 'Technology': [3, 18, 20, 25, 31, 36, 51, 54, 77, 110, 113, 133, 150, 157, 158, 164, 173, 194, 219, 220, 230, 233, 284, 295, 300, 308, 313, 331, 385, 386, 400, 408, 409, 422, 451, 462, 464, 487, 491, 504, 505, 508, 513, 519, 524, 532, 543, 552, 563, 565, 584, 589, 593, 594, 612, 632, 634, 638, 649, 659, 673, 676, 678, 682, 688, 700, 725, 733, 736, 753, 760, 769, 778, 805, 830, 834, 842, 854, 864, 871, 888, 891, 893, 896, 904, 905, 906, 909, 912, 914, 919, 927, 931, 943, 944, 946, 956, 970, 971, 975, ...], 'Telecommunications': [10, 13, 37, 116, 159, 187, 292, 333, 399, 443, 461, 496, 526, 619, 786], 'Transportation': [48, 58, 67, 68, 80, 129, 142, 208, 239, 270, 353, 390, 395, 405, 407, 416, 432, 459, 521, 528, 570, 578, 642, 672, 709, 713, 740, 800, 814, 858, 884, 930, 933, 945, 972, 974], 'Wholesalers': [57, 64, 92, 102, 108, 119, 122, 167, 183, 185, 212, 276, 285, 315, 317, 320, 323, 335, 351, 357, 369, 391, 423, 463, 474, 477, 484, 564, 581, 599, 627, 653, 685, 727, 747, 780, 808, 837, 875, 991]}

## Retrieve A Group with the .get_group() Method

In [28]:
sectors.get_group("Energy")

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
14,Chevron,Energy,Petroleum Refining,"San Ramon, CA",131118,4587,61500
30,Phillips 66,Energy,Petroleum Refining,"Houston, TX",87169,4227,14000
32,Valero Energy,Energy,Petroleum Refining,"San Antonio, TX",81824,3990,10103
42,Marathon Petroleum,Energy,Petroleum Refining,"Findlay, OH",64566,2852,45440
...,...,...,...,...,...,...,...
981,WPX Energy,Energy,"Mining, Crude-Oil Production","Tulsa, OK",1958,-1727,1040
983,Adams Resources & Energy,Energy,Petroleum Refining,"Houston, TX",1944,-1,809
995,EP Energy,Energy,"Mining, Crude-Oil Production","Houston, TX",1908,-3748,665
997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646
997,Portland General Electric,Energy,Utilities: Gas and Electric,"Portland, OR",1898,172,2646

## Methods on the GroupBy and DataFrame Columns

In [32]:
# .max() provides the maximum in the sectors
# .min() provides the minimum in the sectors
# .sum() creates a dataframe with sums in all numeric columns
sectors.max()
sectors.min()
sectors.sum()
sectors.mean()

                                   Revenue      Profits     Employees
Sector
Aerospace & Defense           17897.000000  1437.100000  48402.850000
Apparel                        6397.866667   549.066667  23093.133333
Business Services              5337.156863   553.470588  26687.254902
Chemicals                      8129.900000   754.266667  15455.033333
Energy                        12441.057377  -602.024590   9745.303279
Engineering & Construction     5922.423077   204.000000  15642.615385
Financials                    15950.784173  1872.007194  24172.287770
Food and Drug Stores          32251.266667  1117.266667  93026.533333
Food, Beverages & Tobacco     12929.465116  1195.744186  28177.488372
Health Care                   21529.426667  1414.853333  35710.520000
Hotels, Resturants & Leisure   6781.840000   827.880000  99369.800000
Household Products             8383.464286   515.285714  23072.785714
Industrials                   10816.978261   451.391304  33591.934783
Materials                      6026.627907   102.976744  14840.069767
Media                          8830.560000   973.880000  22012.560000
Motor Vehicles & Parts        20105.833333  1079.083333  45106.666667
Retailing                     18313.450000   597.875000  77845.362500
Technology                    13505.882353  1769.343137  35087.735294
Telecommunications            30788.933333  3242.466667  55497.866667
Transportation                11347.444444  1226.916667  42688.694444
Wholesalers                   11120.000000   205.825000  13139.925000

In [35]:
# Targetting individual columns: 
sectors["Revenue"].sum()

Sector
Aerospace & Defense              357940
Apparel                           95968
Business Services                272195
Chemicals                        243897
Energy                          1517809
Engineering & Construction       153983
Financials                      2217159
Food and Drug Stores             483769
Food, Beverages & Tobacco        555967
Health Care                     1614707
Hotels, Resturants & Leisure     169546
Household Products               234737
Industrials                      497581
Materials                        259145
Media                            220764
Motor Vehicles & Parts           482540
Retailing                       1465076
Technology                      1377600
Telecommunications               461834
Transportation                   408508
Wholesalers                      444800
Name: Revenue, dtype: int64

In [37]:
# Can extract multiple columns by providing a list: 
sectors[["Revenue", "Profits"]].sum()

                              Revenue  Profits
Sector
Aerospace & Defense            357940    28742
Apparel                         95968     8236
Business Services              272195    28227
Chemicals                      243897    22628
Energy                        1517809   -73447
Engineering & Construction     153983     5304
Financials                    2217159   260209
Food and Drug Stores           483769    16759
Food, Beverages & Tobacco      555967    51417
Health Care                   1614707   106114
Hotels, Resturants & Leisure   169546    20697
Household Products             234737    14428
Industrials                    497581    20764
Materials                      259145     4428
Media                          220764    24347
Motor Vehicles & Parts         482540    25898
Retailing                     1465076    47830
Technology                    1377600   180473
Telecommunications             461834    48637
Transportation                 408508    44169
Wholesalers                    444800     8233

## Grouping by Multiple Columns

In [39]:
fortune = pd.read_csv("fortune1000.csv", index_col = "Rank")
sectors = fortune.groupby(["Sector", "Industry"])
fortune.head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000

In [40]:
# Multiple sectors also have multiple industries
sectors.size()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            20
Apparel              Apparel                                          15
Business Services    Advertising, marketing                            2
                     Diversified Outsourcing Services                 14
                     Education                                         3
                                                                      ..
Transportation       Trucking, Truck Leasing                           9
Wholesalers          Miscellaneous                                     1
                     Wholesalers: Diversified                         25
                     Wholesalers: Electronics and Office Equipment     8
                     Wholesalers: Food and Grocery                     6
Length: 79, dtype: int64

In [41]:
sectors.sum()

                                                                   Revenue  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                           357940
Apparel             Apparel                                          95968
Business Services   Advertising, marketing                           22748
                    Diversified Outsourcing Services                 64829
                    Education                                         7485
...                                                                    ...
Transportation      Trucking, Truck Leasing                          35950
Wholesalers         Miscellaneous                                     8982
                    Wholesalers: Diversified                        176138
                    Wholesalers: Electronics and Office Equipment   147906
                    Wholesalers: Food and Grocery                   111774

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                            28742
Apparel             Apparel                                           8236
Business Services   Advertising, marketing                            1549
                    Diversified Outsourcing Services                  4305
                    Education                                           69
...                                                                    ...
Transportation      Trucking, Truck Leasing                           1910
Wholesalers         Miscellaneous                                       17
                    Wholesalers: Diversified                          5193
                    Wholesalers: Electronics and Office Equipment     1857
                    Wholesalers: Food and Grocery                     1166

                                                                   Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                             968057
Apparel             Apparel                                           346397
Business Services   Advertising, marketing                            124100
                    Diversified Outsourcing Services                  708330
                    Education                                          46755
...                                                                      ...
Transportation      Trucking, Truck Leasing                           170456
Wholesalers         Miscellaneous                                       9200
                    Wholesalers: Diversified                          233831
                    Wholesalers: Electronics and Office Equipment     166661
                    Wholesalers: Food and Grocery                     115905

[79 rows x 3 columns]

In [42]:
sectors["Revenue"].sum()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            357940
Apparel              Apparel                                           95968
Business Services    Advertising, marketing                            22748
                     Diversified Outsourcing Services                  64829
                     Education                                          7485
                                                                       ...
Transportation       Trucking, Truck Leasing                           35950
Wholesalers          Miscellaneous                                      8982
                     Wholesalers: Diversified                         176138
                     Wholesalers: Electronics and Office Equipment    147906
                     Wholesalers: Food and Grocery                    111774
Name: Revenue, Length: 79, dtype: int64

In [43]:
sectors["Employees"].mean()

Sector               Industry
Aerospace & Defense  Aerospace and Defense                            48402.850000
Apparel              Apparel                                          23093.133333
Business Services    Advertising, marketing                           62050.000000
                     Diversified Outsourcing Services                 50595.000000
                     Education                                        15585.000000
                                                                          ...
Transportation       Trucking, Truck Leasing                          18939.555556
Wholesalers          Miscellaneous                                     9200.000000
                     Wholesalers: Diversified                          9353.240000
                     Wholesalers: Electronics and Office Equipment    20832.625000
                     Wholesalers: Food and Grocery                    19317.500000
Name: Employees, Length: 79, dtype: float64

## The .agg() Method

In [44]:
# Reset DataFrame
fortune = pd.read_csv("fortune1000.csv", index_col = "Rank")
sectors = fortune.groupby(["Sector", "Industry"])
fortune.head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000

In [45]:
# Using .agg() allows using different methods in each column
# Provide a dict:  key = column name, value = method
sectors.agg({"Revenue" : "sum",
            "Profits" : "sum", 
            "Employees" : "mean"})

                                                                   Revenue  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                           357940
Apparel             Apparel                                          95968
Business Services   Advertising, marketing                           22748
                    Diversified Outsourcing Services                 64829
                    Education                                         7485
...                                                                    ...
Transportation      Trucking, Truck Leasing                          35950
Wholesalers         Miscellaneous                                     8982
                    Wholesalers: Diversified                        176138
                    Wholesalers: Electronics and Office Equipment   147906
                    Wholesalers: Food and Grocery                   111774

                                                                   Profits  \
Sector              Industry
Aerospace & Defense Aerospace and Defense                            28742
Apparel             Apparel                                           8236
Business Services   Advertising, marketing                            1549
                    Diversified Outsourcing Services                  4305
                    Education                                           69
...                                                                    ...
Transportation      Trucking, Truck Leasing                           1910
Wholesalers         Miscellaneous                                       17
                    Wholesalers: Diversified                          5193
                    Wholesalers: Electronics and Office Equipment     1857
                    Wholesalers: Food and Grocery                     1166

                                                                      Employees
Sector              Industry
Aerospace & Defense Aerospace and Defense                          48402.850000
Apparel             Apparel                                        23093.133333
Business Services   Advertising, marketing                         62050.000000
                    Diversified Outsourcing Services               50595.000000
                    Education                                      15585.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                        18939.555556
Wholesalers         Miscellaneous                                   9200.000000
                    Wholesalers: Diversified                        9353.240000
                    Wholesalers: Electronics and Office Equipment  20832.625000
                    Wholesalers: Food and Grocery                  19317.500000

[79 rows x 3 columns]

In [46]:
# Provide a list of methods to apply to each column
sectors.agg(["size", "sum", "mean"])

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\521139243.py:1: FutureWarning: ['Company', 'Location'] did not aggregate successfully. If any error is raised this will raise in a future version of pandas. Drop these columns/ops to avoid this warning.
  sectors.agg(["size", "sum", "mean"])

                                                                  Revenue  \
                                                                     size
Sector              Industry
Aerospace & Defense Aerospace and Defense                              20
Apparel             Apparel                                            15
Business Services   Advertising, marketing                              2
                    Diversified Outsourcing Services                   14
                    Education                                           3
...                                                                   ...
Transportation      Trucking, Truck Leasing                             9
Wholesalers         Miscellaneous                                       1
                    Wholesalers: Diversified                           25
                    Wholesalers: Electronics and Office Equipment       8
                    Wholesalers: Food and Grocery                       6

                                                                           \
                                                                      sum
Sector              Industry
Aerospace & Defense Aerospace and Defense                          357940
Apparel             Apparel                                         95968
Business Services   Advertising, marketing                          22748
                    Diversified Outsourcing Services                64829
                    Education                                        7485
...                                                                   ...
Transportation      Trucking, Truck Leasing                         35950
Wholesalers         Miscellaneous                                    8982
                    Wholesalers: Diversified                       176138
                    Wholesalers: Electronics and Office Equipment  147906
                    Wholesalers: Food and Grocery                  111774

                                                                                 \
                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace and Defense                          17897.000000
Apparel             Apparel                                         6397.866667
Business Services   Advertising, marketing                         11374.000000
                    Diversified Outsourcing Services                4630.642857
                    Education                                       2495.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                         3994.444444
Wholesalers         Miscellaneous                                   8982.000000
                    Wholesalers: Diversified                        7045.520000
                    Wholesalers: Electronics and Office Equipment  18488.250000
                    Wholesalers: Food and Grocery                  18629.000000

                                                                  Profits  \
                                                                     size
Sector              Industry
Aerospace & Defense Aerospace and Defense                              20
Apparel             Apparel                                            15
Business Services   Advertising, marketing                              2
                    Diversified Outsourcing Services                   14
                    Education                                           3
...                                                                   ...
Transportation      Trucking, Truck Leasing                             9
Wholesalers         Miscellaneous                                       1
                    Wholesalers: Diversified                           25
                    Wholesalers: Electronics and Office Equipment       8
                    Wholesalers: Food and Grocery                       6

                                                                          \
                                                                     sum
Sector              Industry
Aerospace & Defense Aerospace and Defense                          28742
Apparel             Apparel                                         8236
Business Services   Advertising, marketing                          1549
                    Diversified Outsourcing Services                4305
                    Education                                         69
...                                                                  ...
Transportation      Trucking, Truck Leasing                         1910
Wholesalers         Miscellaneous                                     17
                    Wholesalers: Diversified                        5193
                    Wholesalers: Electronics and Office Equipment   1857
                    Wholesalers: Food and Grocery                   1166

                                                                                \
                                                                          mean
Sector              Industry
Aerospace & Defense Aerospace and Defense                          1437.100000
Apparel             Apparel                                         549.066667
Business Services   Advertising, marketing                          774.500000
                    Diversified Outsourcing Services                307.500000
                    Education                                        23.000000
...                                                                        ...
Transportation      Trucking, Truck Leasing                         212.222222
Wholesalers         Miscellaneous                                    17.000000
                    Wholesalers: Diversified                        207.720000
                    Wholesalers: Electronics and Office Equipment   232.125000
                    Wholesalers: Food and Grocery                   194.333333

                                                                  Employees  \
                                                                       size
Sector              Industry
Aerospace & Defense Aerospace and Defense                                20
Apparel             Apparel                                              15
Business Services   Advertising, marketing                                2
                    Diversified Outsourcing Services                     14
                    Education                                             3
...                                                                     ...
Transportation      Trucking, Truck Leasing                               9
Wholesalers         Miscellaneous                                         1
                    Wholesalers: Diversified                             25
                    Wholesalers: Electronics and Office Equipment         8
                    Wholesalers: Food and Grocery                         6

                                                                           \
                                                                      sum
Sector              Industry
Aerospace & Defense Aerospace and Defense                          968057
Apparel             Apparel                                        346397
Business Services   Advertising, marketing                         124100
                    Diversified Outsourcing Services               708330
                    Education                                       46755
...                                                                   ...
Transportation      Trucking, Truck Leasing                        170456
Wholesalers         Miscellaneous                                    9200
                    Wholesalers: Diversified                       233831
                    Wholesalers: Electronics and Office Equipment  166661
                    Wholesalers: Food and Grocery                  115905


                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace and Defense                          48402.850000
Apparel             Apparel                                        23093.133333
Business Services   Advertising, marketing                         62050.000000
                    Diversified Outsourcing Services               50595.000000
                    Education                                      15585.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                        18939.555556
Wholesalers         Miscellaneous                                   9200.000000
                    Wholesalers: Diversified                        9353.240000
                    Wholesalers: Electronics and Office Equipment  20832.625000
                    Wholesalers: Food and Grocery                  19317.500000

[79 rows x 9 columns]

In [47]:
# Another way to use .agg()
sectors.agg({"Revenue" : ["sum", "mean"],
            "Profits" : "sum", 
            "Employees" : "mean"})

                                                                  Revenue  \
                                                                      sum
Sector              Industry
Aerospace & Defense Aerospace and Defense                          357940
Apparel             Apparel                                         95968
Business Services   Advertising, marketing                          22748
                    Diversified Outsourcing Services                64829
                    Education                                        7485
...                                                                   ...
Transportation      Trucking, Truck Leasing                         35950
Wholesalers         Miscellaneous                                    8982
                    Wholesalers: Diversified                       176138
                    Wholesalers: Electronics and Office Equipment  147906
                    Wholesalers: Food and Grocery                  111774

                                                                                 \
                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace and Defense                          17897.000000
Apparel             Apparel                                         6397.866667
Business Services   Advertising, marketing                         11374.000000
                    Diversified Outsourcing Services                4630.642857
                    Education                                       2495.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                         3994.444444
Wholesalers         Miscellaneous                                   8982.000000
                    Wholesalers: Diversified                        7045.520000
                    Wholesalers: Electronics and Office Equipment  18488.250000
                    Wholesalers: Food and Grocery                  18629.000000

                                                                  Profits  \
                                                                      sum
Sector              Industry
Aerospace & Defense Aerospace and Defense                           28742
Apparel             Apparel                                          8236
Business Services   Advertising, marketing                           1549
                    Diversified Outsourcing Services                 4305
                    Education                                          69
...                                                                   ...
Transportation      Trucking, Truck Leasing                          1910
Wholesalers         Miscellaneous                                      17
                    Wholesalers: Diversified                         5193
                    Wholesalers: Electronics and Office Equipment    1857
                    Wholesalers: Food and Grocery                    1166

                                                                      Employees
                                                                           mean
Sector              Industry
Aerospace & Defense Aerospace and Defense                          48402.850000
Apparel             Apparel                                        23093.133333
Business Services   Advertising, marketing                         62050.000000
                    Diversified Outsourcing Services               50595.000000
                    Education                                      15585.000000
...                                                                         ...
Transportation      Trucking, Truck Leasing                        18939.555556
Wholesalers         Miscellaneous                                   9200.000000
                    Wholesalers: Diversified                        9353.240000
                    Wholesalers: Electronics and Office Equipment  20832.625000
                    Wholesalers: Food and Grocery                  19317.500000

[79 rows x 4 columns]

## Iterating through Groups

In [48]:
# Reset DataFrame
fortune = pd.read_csv("fortune1000.csv", index_col = "Rank")
sectors = fortune.groupby(["Sector", "Industry"])
fortune.head(3)

,Company,Sector,Industry,Location,Revenue,Profits,Employees
Rank,,,,,,,
1,Walmart,Retailing,General Merchandisers,"Bentonville, AR",482130,14694,2300000
2,Exxon Mobil,Energy,Petroleum Refining,"Irving, TX",246204,16150,75600
3,Apple,Technology,"Computers, Office Equipment","Cupertino, CA",233715,53394,110000

In [49]:
df = pd.DataFrame(columns = fortune.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [50]:
for sector, data in sectors: 
    highest_revenue_comnpany_in_group = data.nlargest(1, "Revenue")
    df = df.append(highest_revenue_comnpany_in_group)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\2137686747.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_comnpany_in_group)

In [51]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
24,Boeing,Aerospace & Defense,Aerospace and Defense,"Chicago, IL",96114,5176,161400
91,Nike,Apparel,Apparel,"Beaverton, OR",30601,3273,62600
186,Omnicom Group,Business Services,"Advertising, marketing","New York, NY",15134,1094,74900
199,Aramark,Business Services,Diversified Outsourcing Services,"Philadelphia, PA",14329,236,216500
737,Graham Holdings,Business Services,Education,"Arlington, VA",2984,-101,11585
...,...,...,...,...,...,...,...
395,Ryder System,Transportation,"Trucking, Truck Leasing","Miami, FL",6572,305,33100
315,Univar,Wholesalers,Miscellaneous,"Downers Grove, IL",8982,17,9200
92,World Fuel Services,Wholesalers,Wholesalers: Diversified,"Miami, FL",30380,187,4700
64,Ingram Micro,Wholesalers,Wholesalers: Electronics and Office Equipment,"Irvine, CA",43026,215,27700
57,Sysco,Wholesalers,Wholesalers: Food and Grocery,"Houston, TX",48681,687,51700

In [52]:
cities = fortune.groupby("Location")
df = pd.DataFrame(columns = fortune.columns)
df

Empty DataFrame
Columns: [Company, Sector, Industry, Location, Revenue, Profits, Employees]
Index: []

In [54]:
for city, data in cities:
    highest_revenue_in_city = data.nlargest(1, "Revenue")
    df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)
C:\Users\manuel.clemente\AppData\Local\Temp\ipykernel_12276\209291239.py:3: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df = df.append(highest_revenue_in_city)

In [55]:
df

,Company,Sector,Industry,Location,Revenue,Profits,Employees
138,Abbott Laboratories,Health Care,Medical Products and Equipment,"Abbott Park, IL",20661,4423,74000
169,Goodyear Tire & Rubber,Motor Vehicles & Parts,Motor Vehicles and Parts,"Akron, OH",16443,307,66000
288,Air Products & Chemicals,Chemicals,Chemicals,"Allentown, PA",9895,1278,19550
830,Benchmark Electronics,Technology,Semiconductors and Other Electronic Components,"Angleton, TX",2541,95,10500
374,Casey’s General Stores,Retailing,Specialty Retailers: Other,"Ankeny, IA",7052,181,22408
...,...,...,...,...,...,...,...
7,CVS Health,Food and Drug Stores,Food and Drug Stores,"Woonsocket, RI",153290,5237,199000
506,Hanover Insurance Group,Financials,Insurance: Property and Casualty (Stock),"Worcester, MA",5034,332,4800
764,Penn National Gaming,"Hotels, Resturants & Leisure","Hotels, Casinos, Resorts","Wyomissing, PA",2838,1,18204
773,Bon-Ton Stores,Retailing,General Merchandisers,"York, PA",2790,-57,24100
932,Herman Miller,Household Products,"Home Equipment, Furnishings","Zeeland, MI",2142,98,7510